variables:
  GIT_SUBMODULE_FORCE_HTTPS: "true" # rewrite git:// submodule urls to https
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --jobs 16
  GIT_STRATEGY: fetch

include:
  - component: $CI_SERVER_FQDN/CGG-public/ci-components/debian-linux/debian@v0.0.10
    inputs:
      stage: build
      tags:
        - cgg
        - linux
        - docker-docker
      debian_release: trixie
  - component: $CI_SERVER_FQDN/CGG-public/ci-components/windows/vs22-cmake@v0.0.12
    inputs:
      stage: build
      tags:
        - cgg
        - win25
        - docker-windows
      after_script:
        - 'dependencies.exe -depth 1 -modules ${Env:BUILD_DIR}/Build/bin/comiso_tests.exe'
