// Build time dependencies for CoMiso

#define COMISO_QT_AVAILABLE 0
#define COMISO_BOOST_AVAILABLE 0
#define COMISO_BLAS_AVAILABLE 1
#define COMISO_GMM_AVAILABLE 1
#define COMISO_ADOLC_AVAILABLE 0
#define COMISO_SUITESPARSE_AVAILABLE 0
#define COMISO_SUITESPARSE_SPQR_AVAILABLE 0
#define COMISO_MPI_AVAILABLE 0
#define COMISO_HSL_AVAILABLE 0
#define COMISO_PETSC_AVAILABLE 0
#define COMISO_TAO_AVAILABLE 0
#define COMISO_IPOPT_AVAILABLE 1
#define COMISO_MUMPS_AVAILABLE 1
#define COMISO_METIS_AVAILABLE 1
#define COMISO_CGAL_AVAILABLE 1
#define COMISO_TAUCS_AVAILABLE 0
#define COMISO_GUROBI_AVAILABLE 0
#define COMISO_ARPACK_AVAILABLE 0
#define COMISO_CPLEX_AVAILABLE 0
#define COMISO_EIGEN3_AVAILABLE 1
#define COMISO_DCO_AVAILABLE 0
#define COMISO_CBC_AVAILABLE 0
#define COMISO_CLP_AVAILABLE 0
#define COMISO_CGL_AVAILABLE 0
#define COMISO_COINUTILS_AVAILABLE 0
#define COMISO_DOCLOUD_AVAILABLE 1